DefaultContentLanguage = "zh"
autoFigure = true
baseURL = "https://www.qikqiak.com/"
canonifyURLs = true
googleAnalytics = "UA-69668147-3"
languageCode = "en-us"
paginate = 12
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "dracula"
pygmentsUseClasses = false
pygmentsUseClassic = false
theme = "beautifulhugo"
title = "阳明的博客"
[[menu.main]]
name = "RSS"
url = "index.xml"
weight = 9
[[menu.main]]
name = "About"
url = "page/about/"
weight = 7
[[menu.main]]
name = "Golang microservices"
parent = "book"
url = "/tdd-book/"
weight = 5
[[menu.main]]
identifier = "book"
name = "books"
weight = 6
[[menu.main]]
name = "devops"
parent = "categories"
url = "tags/devops"
weight = 8
[[menu.main]]
name = "kubernetes"
parent = "categories"
url = "tags/kubernetes"
weight = 4
[[menu.main]]
name = "tags"
parent = "categories"
url = "tags"
weight = 1
[[menu.main]]
name = "Archive"
parent = "categories"
url = "archives"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 3
[params]
algolia = "8804ac109158bb3bb60d74ce98fa332f"
author = "阳明"
avatar = "https://bxdc-static.oss-cn-beijing.aliyuncs.com/images/blog-favicon.png"
customCSSAssets = []
customJSAssets = []
defaultImg = "https://bxdc-static.oss-cn-beijing.aliyuncs.com/images/photo-1557380664-dd666ff4e559.jpeg"
favicon = "https://bxdc-static.oss-cn-beijing.aliyuncs.com/images/blog-favicon.png"
keywords = "docker、kubernetes、istio、devops、prometheus、python、golang、云原生、微服务"
logo = "https://bxdc-static.oss-cn-beijing.aliyuncs.com/images/blog-favicon.png"
navLogo = "https://bxdc-static.oss-cn-beijing.aliyuncs.com/images/blog-logo-new.png"
reward = true
rss = true
subtitle = "关注 Kubernetes、Istio、DevOps、Prometheus、Python、Golang、云原生、微服务等技术"
useWebfont = true
[params.adsense]
client = "ca-pub-5376999672787220"
inArticleSlot = "5684687044"
textSlot = "9165834656"
[params.gitcomment]
clientId = "bdb76dbb2e9d0786e350"
clientSecret = "b454b2a08013fd0e32013be7a63fa8fcb262b6c4"
owner = "cnych"
repo = "blog"
[[params.banner]]
desc = "打造独当一面的 Kubernetes 运维、开发工程师"
src = "https://bxdc-static.oss-cn-beijing.aliyuncs.com/images/k8s-banner-k8scourse.jpg"
url = "/post/promotion-51/"
[[params.banner]]
desc = "云原生技术公开课"
src = "https://bxdc-static.oss-cn-beijing.aliyuncs.com/images/aliyun-cloudnative-edu1.jpeg"
url = "https://edu.aliyun.com/roadmap/cloudnative?spm=a1z389.11499242.0.0.65452413qdXfZ7&utm_content=g_1000093512"
[[params.banner]]
desc = "优点知识"
src = "https://bxdc-static.oss-cn-beijing.aliyuncs.com/images/k8s-banner-ydzs.jpg"
url = "https://youdianzhishi.com/?utm_source=blog&utm_campaign=referral&utm_medium=banner"
[[params.banner]]
desc = "《深入浅出 Prometheus》"
src = "https://bxdc-static.oss-cn-beijing.aliyuncs.com/images/k8s-banner-promebook.jpg"
url = "https://detail.tmall.com/item.htm?spm=a212k0.12153887.0.0.64a3687dQ6nSzh&id=590161370307"
